# Generated by Django 3.2.3 on 2021-08-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('auth', models.TextField(verbose_name='作者')),
                ('create_data', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('introduce', models.TextField(verbose_name='介绍')),
                ('size', models.TextField(verbose_name='大小')),
                ('version', models.TextField(verbose_name='版本')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_data', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='donorlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='Hots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('auth', models.TextField(verbose_name='作者')),
                ('create_data', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='More',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名字')),
                ('introduce', models.TextField(verbose_name='介绍')),
                ('size', models.TextField(verbose_name='大小')),
                ('version', models.TextField(verbose_name='版本')),
                ('content', models.TextField(verbose_name='内容')),
                ('link', models.TextField(verbose_name='链接')),
                ('create_data', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('isshow', models.TextField(verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('auth', models.TextField(verbose_name='作者')),
                ('create_data', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='名称')),
                ('content', models.TextField(verbose_name='内容')),
                ('auth', models.TextField(verbose_name='作者')),
                ('create_data', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('isdonor', models.CharField(default='非捐赠者', max_length=32)),
                ('create_time', models.DateField(auto_now=True)),
                ('money', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='userToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='home.user')),
            ],
            options={
                'verbose_name': '用户token表',
                'verbose_name_plural': '用户token表',
                'db_table': 'user_token',
            },
        ),
    ]
